# Generated by Django 5.2.3 on 2025-07-15 16:25

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_flashcard_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='document',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PDF', 'PDF Document'), ('IMAGE', 'Image File'), ('TEXT', 'Text Document')], max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'doc', 'docx'])]),
        ),
        migrations.DeleteModel(
            name='Flashcard',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
